### ISSUE TITLE
Project missing from skiselev.github.io ;)

### ISSUE THREAD

**Issue by plaes** [skiselev/lp486pkt#1]
More people should know that this driver exists.. :)

Great work and saved a lot of time for me.

![image](https://github.com/skiselev/lp486pkt/assets/91895/3eaea814-b6fb-41cf-af9b-1ddd862dbe72)

I guess that FAX number could be dropped though?

**Comment by skiselev** [comment]
I merged your pull request. Thank you again!
The fax number comes from the packet driver skeleton. I just dialed the number. It appears to be a fax on the other side ;)
